<?php 
session_start();
include("assets/bin/con_db.php");
 require_once __DIR__ . '/assets/mpdf/vendor/autoload.php';
global $db;
  
     error_reporting(E_ALL);
     ini_set('display_errors', 1);
  if (!isset($_SESSION["exportParams"])) {
     exit();
   }
  $Params = $_SESSION["exportParams"];
   
  $url = "https://churchapp.pceasnyaga.org";
     $mpdf = new \Mpdf\Mpdf([
    'setAutoTopMargin' => 'stretch',
    'autoMarginPadding' => 3,
    'orientation' => 'L'
]);


     $stylesheet = file_get_contents('mpdfstyle.css');
    $mpdf->WriteHTML($stylesheet,1);
  $dateCreated = date('D jS M Y g:i a');

    $mpdf->SetWatermarkImage('assets/images/logo1.jpg');
    $mpdf->showWatermarkImage = true;
    $mpdf->watermarkImageAlpha = 0.1;
 //$db->debug=1;

  $modCode = $Params["modCode"];
  $qrysmt  = $Params["wheresmt"];

  $MView = $rs->getDataTblView($modCode);
  $cols =  $MView["ViewCols"];
  $tableName = $MView["ModInfo"]["TableName"];
  $ModuleName = $MView["ModInfo"]["ModuleName"];
  $ModuleCode = $MView["ModInfo"]["ModuleCode"];
   array_shift($cols);

     $getCols = $db->GetArray("select FieldName,DisplayName from dh_listview where ModuleCode='$ModuleCode'  and ListType='Main' and TableName='$tableName' order by DisplayOrder asc");
    $html ="";
    $html .="<p style='v-align:center;'> <img src='assets/images/logo1.jpg' width='300px' height='52px'></p>";
    $html .="<p style='v-align:center;'><h2>$ModuleName</h2></p>";

     $html .= "<table class='gridtable' width='99%'>";
      $html .= "<thead>";
          $html .= "<tr>";
          $html .= "<th>#</th>";
       foreach ($getCols as $ckey => $cval) {
            $html .= "<th>".$cval["DisplayName"]."</th>";
          }
       $html .= "</tr>";
          $html .= "</thead>";
          $html .= "<tbody>";

          $getdata = $db->Execute("select *from $tableName $qrysmt");
   
   
       $i = 0;
      while (!$getdata->EOF) {
          $rst = array();
          $rst = $getdata->fields;
          $data = array();
          $i=$i+1;
	      $crl = $i%2 ? "alt" : "";
          $html .= "<tr class='$crl'>";
           $html .= "<td>$i</td>";
          foreach ($cols as $key => $val) { 
             $html .= "<td>".$rst[$val]."</td>";
          }
           $html .= "</tr>";

        
        $getdata->MOveNext();
      }

   $html .= "</tbody>";
   $html .= "</table>";
    $foothtml = "<hr/>";
   $foothtml .= "<table width='100%'><tr>";
   $foothtml .= "<td width='33%'>{DATE j-m-Y}</td>";
   $foothtml .= "<td width='33%' align='center'>{PAGENO}/{nbpg}</td>";
   $foothtml .= "<td width='33%' style='text-align: right;'>$ModuleName</td>";
   $foothtml .= "</tr></table>";

   $mpdf->SetHTMLFooter($foothtml);
   
   $mpdf->WriteHTML($html);
      // Set a simple Footer including the page number
  $mpdf->setHeader("Generated by Kevin on $dateCreated");
  $mpdf->Output($ModuleName."_".date('ymdhms').".pdf", "D");   
  //$mpdf->Output();
?>